apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  labels:
    app: webserver-pod
spec:
  containers:
    - name: webserver-pod
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-vol
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"

    - name: sidecar
      image: busybox
      command: [
          "sh",
          "-c",
          "while true; do if [ \"$(cat /var/log/nginx/error.log \
          | grep 'error')\" != \"\" ]; then echo 'Erro descoberto!'; fi; \
          sleep 10; done",
        ]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-vol
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"

  volumes:
    - name: logs-vol
      emptyDir: {}
