apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-dev
  name: nginx-dev
  namespace: dev
spec:
  containers:
    - image: nginx
      name: nginx-dev
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
