apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-replicaset
  labels:
    app: webserver-pod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.19
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
