apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-pod
spec:
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args:
        - "--vm"
        - "2"
        - "--vm-bytes"
        - "128M"
        - "--vm-hang"
        - "2"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
