apiVersion: v1
kind: Pod
metadata:
  labels:
    run: podtest
  name: podtest
  namespace: default
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: podtest
      resources: {}
  restartPolicy: Never
