apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-nodeport
  name: service-port
spec:
  ports:
  - port: 30000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-nodeport
  type: NodePort
status:
  loadBalancer: {}
