# Etapa 1 - builder
FROM golang:1.21 AS builder
WORKDIR /app
ENV GO111MODULE=off
COPY main.go .
RUN go build -o app

# Etapa 2 - imagem final mínima
FROM scratch
COPY --from=builder /app/app .
ENTRYPOINT ["/app"]
