apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Leitura e escrita por um único nó
    # - ReadOnlyMany  # Leitura por múltiplos nós
  persistentVolumeReclaimPolicy: Retain # Política de retenção do volume (Retain e Delete, o Recycle é Depreciado)
  hostPath:
    path: /tmp/hostpath-pv
