apiVersion: v1
kind: Pod
metadata:
  name: pod-test-sa
spec:
  serviceAccountName: test-sa
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          cpu: "0.1"
          memory: "64Mi"
