apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: local-path-storage
  name: list-pods-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create"]

# k create role list-pods-role --verb=get,watch,list,create,delete,update --resource=pods,services --dry-run=client -o yaml > myapp-list-pods-role.yaml
